### ISSUE TITLE
Support 2-way synchronization between C8Y and ADAMOS Hub

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/c8y-adamos-hub-connector#22]
At the moment devices can either be imported from the Hub into Cumulocity or exported from Cumulocity into the hub. There are cases where the device might already exist in both systems. Currently one of them would need to be deleted.

The idea is that during import or export the user can either provide a ADAMOS machine ID or the Cumulocity managed object id. ADAMOS Hub is assumed to be the leading system and any existing hub data in Cumulocity would be overwritten.

**Comment by hnaether-sag** [comment]
Implemented possibility to select existing devices when linking an ADAMOS Hub or Cumulocity IoT Device. Part of version 1.3.6 of the UI project.
