### ISSUE TITLE
Integrate Hub Connector UI with standard applications

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/c8y-adamos-hub-connector#4]

**Comment by hnaether-sag** [comment]
Partly done. It's possible to create a build with the ADAMOS Hub Connector as UI plugin using the new Micro-Frontend-Framework. This way you can add the Hub functionality to any clone of e.g. Cockpit app etc. Unfortunately, this approach is currently not supporting internationalization. That's the reason why the UI project is currently still build as standalone app. We'll leave this open until internationalization is possible.

**Comment by haraldmeyer** [comment]
I thought we will have different versions of the plugin for different languages while internationalization is not supported?

**Comment by hnaether-sag** [comment]
As agreed let's stick with english for now. As soon as the translation feature is available, let's create a new build.
