### ISSUE TITLE
Make dev vs. prod selection of ADAMOS HUB configurable in UI

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/c8y-adamos-hub-connector#8]
The Settings page:
![image](https://user-images.githubusercontent.com/44459397/206161225-6894e0ec-bf34-4503-b839-7adb6e6f1a85.png)

Should have an additional section to configure the ADAMOS Hub instance. The instance should be selectable from a drop-down list with currently the following values:

* adamos-hub.dev
* adamos-hub.com

The selected URL should be part of the HubConnectorGlobalSettings:
https://github.com/SoftwareAG/c8y-adamos-hub-connector/blob/main/ax-mm-hubconnector/src/main/java/com/adamos/hubconnector/model/HubConnectorGlobalSettings.java

The setting should replace the existing app.hubconnector.host setting from the application.properties:
https://github.com/SoftwareAG/c8y-adamos-hub-connector/blob/main/ax-mm-hubconnector/src/main/resources/application.properties

As the other app.hubconnector settings depend on it, the settings in the application.properties should be replaced by a Spring-configured bean. The paths of the individual services do not need to be configurable.

**Comment by hnaether-sag** [comment]
Testing...

**Comment by hnaether-sag** [comment]
Improved migration logics. Instead of empty string, setting https://adamos.hub.com as default url. Waiting for review.
